# Generated by Django 2.2.3 on 2019-08-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogxadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章阅读', 'verbose_name_plural': '文章阅读'},
        ),
    ]
