# Generated by Django 2.2.3 on 2019-08-09 10:02

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogxadmin', '0003_auto_20190808_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情')),
            ],
        ),
    ]
